<?php

/**
 * @file
 * MailChimp eCommerce install and update hooks.
 */

/**
 * Implements hook_uninstall().
 */
function mailchimp_ecommerce_uninstall() {
  \Drupal::config('mailchimp_ecommerce.settings')->clear('mailchimp_ecommerce_store_name')->save();
  \Drupal::config('mailchimp_ecommerce.settings')->clear('mailchimp_ecommerce_list_id')->save();
  \Drupal::config('mailchimp_ecommerce.settings')->clear('mailchimp_ecommerce_opt_in_status')->save();
}
